---
services:
  freqtrade_soundmoney:
    image: freqtradeorg/freqtrade:develop
    restart: unless-stopped
    container_name: freqtrade_soundmoney
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./freqtrade:/freqtrade/freqtrade"
    ports:
      - "8080:8080"
    command: >
      trade --logfile /freqtrade/user_data/logs/freqtrade_soundmoney.log --db-url sqlite:////freqtrade/user_data/tradesv3_soundmoney.sqlite --config /freqtrade/user_data/config_soundmoney.json --strategy SoundMoney254
    networks:
      - screencoins_default

networks:
  screencoins_default:
    external: true
